[package]
name = "wasm_object"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divine = {path = "../divine"}
interface_rs = {path = "../interface_rs"}

[lib]
crate-type = ["cdylib"]
